apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2026-04-12T16:22:27Z"
    generation: 1
    labels:
      app.kubernetes.io/component: app
      app.kubernetes.io/name: linkding
    name: linkding
    namespace: linkding
    resourceVersion: "7280692"
    uid: 2d8b06c8-4069-46a7-a6dc-9ec5a161fb43
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/name: linkding
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app.kubernetes.io/name: linkding
      spec:
        containers:
        - envFrom:
          - secretRef:
              name: linkding-credentials
          image: sissbruecker/linkding:latest-plus
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: linkding
          ports:
          - containerPort: 9090
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/linkding/data
            name: data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 33
        terminationGracePeriodSeconds: 30
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: linkding-data
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-04-12T16:22:27Z"
      lastUpdateTime: "2026-04-12T16:31:55Z"
      message: ReplicaSet "linkding-7cfff665d4" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-05-10T08:16:48Z"
      lastUpdateTime: "2026-05-10T08:16:48Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2026-04-12T16:22:28Z"
    labels:
      app.kubernetes.io/component: service
      app.kubernetes.io/name: linkding
    name: linkding
    namespace: linkding
    resourceVersion: "372800"
    uid: e9afaf97-3906-47f5-9f59-a7478097cacc
  spec:
    clusterIP: 10.43.186.223
    clusterIPs:
    - 10.43.186.223
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: http
    selector:
      app.kubernetes.io/name: linkding
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    creationTimestamp: "2026-04-12T16:22:30Z"
    generation: 1
    labels:
      app.kubernetes.io/component: ingress
      app.kubernetes.io/name: linkding
    name: linkding
    namespace: linkding
    resourceVersion: "7269793"
    uid: 151d0f22-a8c6-4fb5-b03c-5b3eaa0fa5f6
  spec:
    ingressClassName: traefik
    rules:
    - host: linkding.l.thein3rovert.com
      http:
        paths:
        - backend:
            service:
              name: linkding
              port:
                number: 9090
          path: /
          pathType: Prefix
  status:
    loadBalancer:
      ingress:
      - ip: 100.123.5.107
      - ip: 100.85.190.19
      - ip: 100.87.231.18
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2026-04-12T16:22:26Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: storage
      app.kubernetes.io/name: linkding
    name: linkding-data
    namespace: linkding
    resourceVersion: "372781"
    uid: 0a7e0af1-3a1a-4e9a-8fe9-ccc57a0f65d8
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: longhorn
    volumeMode: Filesystem
    volumeName: pvc-0a7e0af1-3a1a-4e9a-8fe9-ccc57a0f65d8
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
