# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ modulesPath, pkgs, ... }:

{
  imports = [
    # Include the default incus configuration.
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Include the container-specific autogenerated configuration.
    ./incus.nix
  ];

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  services.openssh = {
    enable = true;
    settings.PermitRootLogin = "yes";
  };

  # users.users.root.openssh.authorizedKeys.keys = [
  #   "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIObli1unUWlbZaja5VMzTIvPBJOCI/E6vs/qhrVkSHLO thein3rovert"
  # ];

  users.users.thein3rovert = {
    isNormalUser = true;
    extraGroups = [
      "networkmanager"
      "wheel"
    ];
    # Add ssh keys
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIObli1unUWlbZaja5VMzTIvPBJOCI/E6vs/qhrVkSHLO thein3rovert"
    ];
  };
  environment.systemPackages = with pkgs; [
    # Essential system tools
    vim # Text editor
    htop
    git
  ];

  security.sudo.extraRules = [
    {
      users = [ "thein3rovert" ];
      commands = [
        {
          command = "ALL";
          options = [ "NOPASSWD" ];
        }
      ];
    }
  ];

  # nixosSetup = {
  #   services = {
  #     ad-guard.enable = false;
  #     tailscale = {
  #       enable = false;
  #     };
  #   };
  # };

  # networking.nameservers = [
  #   # Default (Adguard)
  #   "10.135.108.203"
  # ];
  #
  # networking.interfaces.eth0 = {
  #   useDHCP = false;
  #   ipv4.addresses = [
  #     {
  #       address = "10.135.108.203";
  #       prefixLength = 24;
  #     }
  #   ];
  # };
  # networking.defaultGateway = "10.135.108.1";
  # Disable router DNS
  networking.networkmanager.dns = "none";
  # services.resolved.enable = false;
  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        Address = "10.135.108.203/24";
        Gateway = "10.135.108.1";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  system.stateVersion = "26.05"; # Did you read the comment?
}
