# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{
  modulesPath,
  pkgs,
  config,
  ...
}:

{
  imports = [
    # Include the default incus configuration.
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Include the container-specific autogenerated configuration.
    ./incus.nix
  ];

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  services.openssh = {
    enable = true;
    # If user == exist, root login is false
    settings.PermitRootLogin = "yes";
  };

  # ==============================
  #       User Management
  # ==============================
  # Users configured with yescrypt password hashing
  myUsers = {
    thein3rovert = {
      enable = true;
      password = "$y$j9T$zPz9u.btt2JUDlLkkMoux.$nqviLDKqy6q.vG9Vl1f4w3jbE/ctd/sIj.AZXjxJyd1";
    };
  };

  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIObli1unUWlbZaja5VMzTIvPBJOCI/E6vs/qhrVkSHLO thein3rovert"
  ];

  users.users.thein3rovert = {
    isNormalUser = true;
    extraGroups = [
      "networkmanager"
      "wheel"
    ];
  };

  environment.systemPackages = with pkgs; [
    vim
    htop
    git
    fastfetch
    openssh
  ];

  security.sudo.extraRules = [
    {
      users = [ "thein3rovert" ];
      commands = [
        {
          command = "ALL";
          options = [ "NOPASSWD" ];
        }
      ];
    }
  ];

  programs.ssh.knownHosts = config.snippets.ssh.knownHosts;
  security.wrappers.ping = {
    source = "${pkgs.iputils}/bin/ping";
    owner = "root";
    group = "root";
    setuid = true;
  };
  nixosSetup = {
    services = {
      ad-guard.enable = false;
      tailscale = {
        enable = true;
      };
    };
  };

  networking.nameservers = [
    # Default (Adguard)
    # "10.135.108.10"
    # "1.1.1.1"
    # "8.8.8.8"
  ];

  # networking.interfaces.eth0 = {
  #   useDHCP = false;
  #   ipv4.addresses = [
  #     {
  #       address = "10.135.108.203";
  #       prefixLength = 24;
  #     }
  #   ];
  # };
  # networking.defaultGateway = "10.135.108.1";

  # Disable router DNS
  # networking.networkmanager.dns = "none";
  services.resolved.enable = false;
  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        Address = "10.135.108.10/24";
        Gateway = "10.135.108.203";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  system.stateVersion = "26.05"; # Did you read the comment?
}
