concurrency:
  cancel-in-progress: true
  # This ensure that on each push only only
  # run is active at a time
  group: ${{ github.workflow }}-${{ github.ref }} # unique "group" name for each workflow run
jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 1
    - uses: DeterminateSystems/nix-installer-action@main
    - name: Check flake evaluation
      run: nix -Lv flake check --all-systems
name: check-nix
'on':
  push:
    paths-ignore:
    - '**/*.md'
    - .github/**
    - _img/**
  workflow_dispatch: {}
