name: terraform-ci

on:
  pull_request:
    paths:
      - 'terraform/**'
  workflow_dispatch: {}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  terraform-validate:
    runs-on: self-hosted
    strategy:
      matrix:
        environment:
          - dev
          - prod
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt check
        id: fmt
        run: terraform fmt -check -recursive
        working-directory: terraform/
        continue-on-error: true

      - name: Terraform init (${{ matrix.environment }})
        id: init
        run: terraform init -backend=false -reconfigure
        working-directory: terraform/envs/${{ matrix.environment }}

      - name: Terraform validate (${{ matrix.environment }})
        id: validate
        run: terraform validate
        working-directory: terraform/envs/${{ matrix.environment }}

      - name: Terraform plan (${{ matrix.environment }})
        id: plan
        run: terraform plan -no-color
        working-directory: terraform/envs/${{ matrix.environment }}
        env:
          TF_VAR_vault_address: ${{ secrets.VAULT_ADDR }}
          TF_VAR_vault_token: ${{ secrets.VAULT_TOKEN }}
        continue-on-error: true

      - name: Comment results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const output = `### Terraform CI Results - ${{ matrix.environment }}
            
            #### Format and Style 🖌 \`${{ steps.fmt.outcome }}\`
            #### Initialization ⚙️ \`${{ steps.init.outcome }}\`
            #### Validation 🤖 \`${{ steps.validate.outcome }}\`
            #### Plan 📖 \`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`terraform
            ${{ steps.plan.outputs.stdout }}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Fail on fmt error
        if: steps.fmt.outcome == 'failure'
        run: |
          echo "Terraform fmt check failed. Run 'terraform fmt -recursive' to fix."
          exit 1

      - name: Fail on plan error
        if: steps.plan.outcome == 'failure'
        run: |
          echo "Terraform plan failed."
          exit 1
